#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 225
#define TAPPING_SHIFT_TERM 150
#define TAPPING_HM_TERM 250
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
